#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace App\Commands;

use System\Console\Command;
use System\Console\Traits\PrinterTrait;

use function System\Console\style;

class __command__Command extends Command
{
    use PrinterTrait;

    /**
     * Register command.
     *
     * @var array<int, array<string, mixed>>
     */
    public static array $command = [
        [
            "cmd"       => "__command__",
            "mode"      => "full",
            "class"     => self::class,
            "fn"        => "main",
        ],
    ];

    /**
     * @return array<string, array<string, string|string[]>>
     */
    public function printHelp()
      {
          return [
              'commands' => [],
              'options'  => [],
              'relation' => [],
          ];
      }

    public function main(): int
    {
        style("__command__")->out(false);

        return 0;
    }
}
