#!/usr/bin/env php
<?php

namespace Model\@__model__;

use System\Database\MyCRUD;
use System\Database\MyPDO;

class __model__ extends MyCRUD
{
    // getter
    public function getID()
    {
      return $this->ID['id'] ?? null;
    }

    // getter __getter__

    // setter
    public function setID(int $val)
    {
      $this->ID = array (
        'id' => $val
      );
      return $this;
    }

    // setter __setter__

    public function __construct()
    {
      $this->PDO = new MyPDO();
      $this->TABLE_NAME = '__table__';
      $this->COLUMNS = [
        __column__
      ];
    }
}
