#!/usr/bin/env php
<?php

namespace App\Model\@__model__;

use System\Database\MyCRUD;
use System\Support\Facades\PDO;

class __model__ extends MyCRUD
{
    public function __construct()
    {
      $this->PDO = PDO::instance();
      $this->TABLE_NAME = '__table__';
      $this->COLUMNS = [
        // __column__
      ];
    }
}
