#!/usr/bin/env php
<?php

namespace App\Models\__model__;

use System\Database\MyCRUD;
use System\Support\Facades\PDO;

class __model__ extends MyCRUD
{
    protected $TABLE_NAME = '__table__';

    protected $PRIMERY_KEY = '__primery__';
    
    protected $COLUMNS = [
        // __column__
    ];
    
    public function __construct()
    {
        $this->PDO = PDO::instance();
    }
}
