name: Bug Report
description: Help us improve by reporting bugs or issues
labels:
  - Bug
body:
  - type: input
    id: impacted-version
    attributes:
      label: PHP-MVC Version
      placeholder: x.y.z
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: 8.1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to reproduce the behavior:
        1. '...'
        2. '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Explain what you expected to happen instead.

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Context
      description: Any other details you think might be relevant, including potential solutions.
