name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for your pull request. However, this repository is a read-only sub-split. Please submit your PR to https://github.com/sonypradana/php-library instead. Thanks!"
