name: PHP UnitTets

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.4, 8.0, 8.1]

    name: Tests PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ matrix.os }}-composer-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --dev --prefer-dist --no-progress --no-suggest

    - name: reload autoload
      run: composer dump-autoload

    - name: Run test suite
      run: composer test:unit tests/
