name: Static Analysis

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  cs:
    runs-on: ubuntu-latest

    name: Code Style

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --no-interaction --no-progress --ansi

    - name: Run PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix -v --allow-risky=yes --dry-run --ansi

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-stable]

    name: PHPStan ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --no-interaction --no-progress --ansi

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --debug --ansi
      
  refacto:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-stable]

    name: Rector ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --no-interaction --no-progress --ansi

    - name: Run Rector
      run: vendor/bin/rector --dry-run
      
  split-repo:
    runs-on: ubuntu-latest
    name: Split repo validation Check

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2

    - name: Install Dependencies
      run: composer update --no-interaction --no-progress --ansi

    - name: Validate split repo
      run: composer test:release
